DjebbzBlogBundle_homepage:
    pattern: /
    defaults: { _controller: DjebbzBlogBundle:Page:index }
    requirements:
        _method: GET

DjebbzBlogBundle_about:
    pattern: /about
    defaults: { _controller: DjebbzBlogBundle:Page:about }
    requirements:
        _method: GET

DjebbzBlogBundle_contact:
    pattern:   /contact
    defaults:  { _controller: DjebbzBlogBundle:Page:contact }
    requirements:
        _method: GET|POST